chore(internal/gencli): fix error strings and delete unused code (#1402)
The following errors were reported by staticcheck and are fixed in this PR:

internal/gencli/gencli.go:730:10: error strings should not be capitalized (ST1005)
internal/gencli/gencli.go:736:11: error strings should not be capitalized (ST1005)
internal/gencli/gencli.go:761:11: error strings should not be capitalized (ST1005)
internal/gencli/gencli.go:766:10: error strings should not be capitalized (ST1005)
internal/gencli/gencli.go:770:10: error strings should not be capitalized (ST1005)
internal/gencli/util.go:63:6: func strContains is unused (U1000)